server.port: 8080

spring:
  application:
    name: client

security:
  oauth2:
    client:
      accessTokenUri: http://api-gateway:8765/uaa/oauth/token
#      accessTokenUri: http://localhost:8765/uaa/oauth/token
      userAuthorizationUri: http://api-gateway:8765/uaa/oauth/authorize
#      userAuthorizationUri: http://localhost:8765/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
      grant-type: password
  basic:
    enabled: false

logging.level.org.springframework.security: DEBUG

eureka:
  instance:
    hostname: localhost
    port: 8761
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/

---

spring:
  profiles: docker

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: ${REGISTRY_URL}